# Generated by Django 4.2.6 on 2023-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="special_request",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.CharField(
                choices=[("Chinese", "中文:Chinese"), ("English", "English")],
                default="English",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Wechat", "微信朋友圈: WeChat Moments"),
                    ("Xiaohongshu", "小红书:Xiaohongshu"),
                    ("1x_website", "1x Website"),
                ],
                default="Wechat",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="photo_category",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
