# Generated by Django 4.2.6 on 2023-10-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_generate_text_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postaudio",
            name="page_id",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="postaudio",
            name="request",
            field=models.TextField(default="no record"),
        ),
    ]
