# Generated by Django 4.2.6 on 2023-10-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_postaudio_page_id_alter_postaudio_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postaudio",
            name="page_id",
        ),
        migrations.AddField(
            model_name="postaudio",
            name="chat_id",
            field=models.CharField(default="0", max_length=20, unique=True),
        ),
    ]
