# Generated by Django 4.2.6 on 2023-10-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_postaudio_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name='post_photo_category',  # 请将NewTableName更改为你的模型名称
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField()),
                ('category_id', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="special_request",
            field=models.TextField(default=""),
        ),
    ]
