# Generated by Django 4.2.6 on 2023-11-01 21:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_photo_category_options_alter_post_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
