# Generated by Django 4.2.6 on 2023-11-07 15:48

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_gptimage_alter_post_photo_category_options_and_more"),
    ]

    operations = [

        migrations.RemoveField(
            model_name="gptimage",
            name="conversation_id",
        ),
        migrations.AddField(
            model_name="gptimage",
            name="conversation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.conversation",
            ),
        ),

    ]
