# Generated by Django 4.2.6 on 2023-11-08 15:41

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_post_photo_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image_url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
