# Generated by Django 4.2.6 on 2023-11-08 16:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_post_photo_category_options_and_more"),
    ]

    operations = [

        migrations.RenameField(
            model_name="chatmessage",
            old_name="image_url",
            new_name="imageUrl",
        ),

    ]
