# Generated by Django 4.2.6 on 2023-11-24 16:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_post_photo_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyusage",
            name="total_count",
            field=models.IntegerField(default=0),
        ),

    ]

# 删除
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ("blog", "0019_alter_post_photo_category_options_and_more"),
#     ]
#
#     operations = [
#         migrations.AlterModelOptions(
#             name="post_photo_category",
#             options={"managed": False},
#         ),
#         migrations.AlterField(
#             model_name="post",
#             name="file",
#             field=models.FileField(
#                 blank=True, null=True, upload_to=blog.models.user_directory_path
#             ),
#         ),
#         migrations.AlterField(
#             model_name="post",
#             name="photo_category",
#             field=models.ManyToManyField(
#                 through="blog.Post_Photo_Category", to="blog.category"
#             ),
#         ),
#         migrations.AlterField(
#             model_name="postaudio",
#             name="chat_id",
#             field=models.CharField(default="0", max_length=255),
#         ),
#     ]
