# Generated by Django 4.2.6 on 2025-03-17 10:54

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_alter_post_photo_category_options_and_more'),
    ]

    # 删除！
    # operations = [
    #     migrations.CreateModel(
    #         name='Post_Photo_Category',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #         ],
    #         options={
    #             'managed': False,
    #         },
    #     ),
    #     migrations.AlterField(
    #         model_name='post',
    #         name='file',
    #         field=models.FileField(blank=True, null=True, upload_to=blog.models.user_directory_path),
    #     ),
    #     migrations.AlterField(
    #         model_name='postaudio',
    #         name='chat_id',
    #         field=models.CharField(default='0', max_length=255),
    #     ),
    #     migrations.CreateModel(
    #         name='EmailAccount',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('email', models.EmailField(max_length=254)),
    #             ('password', models.CharField(max_length=255)),
    #             ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
    #         ],
    #     ),
    #     migrations.AlterField(
    #         model_name='post',
    #         name='photo_category',
    #         field=models.ManyToManyField(through='blog.Post_Photo_Category', to='blog.category'),
    #     ),
    # ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]